version: '3.8'

services:
  db:
    image: postgres:16.2-alpine
    restart: always
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./ecommerce-backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Use as mesmas variáveis de ambiente do banco de dados
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  frontend:
    build: ./ecommerce-frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "5173:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend

env_file:
  - .env

volumes:
  db-data: